### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by SingleSlice** [UNICT-DMI/Telegram-SpottedDMI-Bot#115]
Did you know? Rust is blazingly fast, it would make the bot blazingly faster, so fast, woah, and also, memory safe !!! :rocket: :fire: :crab:

**Comment by Helias** [comment]
We have no the developer power to do that, specially to maintain it
Python is easier to learn and to use for beginners, so we will not switch to Rust, at least for now it's not in our plan

**Comment by Herbrant** [comment]
I think it's just a meme
