### ISSUE TITLE
Reject Spot 

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/Telegram-SpottedDMI-Bot#13]
It's better to reject a spot when just **only one** admin reject it.

**Comment by TendTo** [comment]
To achieve this goal, this change would be needed (file _modules/handlers/callback_handlers.py_ lines 188-189):
from
``` python   
# The post has been refused
if n_reject >= config_map['meme']['n_votes']:
```
to 
``` python   
# The post has been refused
if n_reject >= 1:
```

But personally, i prefer like this (let's export some democracy)

**Comment by Helias** [comment]
I think that for this case we can consider **unanimity**, if there is someone who wants to reject a spot, it's better to reject first and discuss later to prevent any scandal :grin:

**Comment by alepiaz** [comment]
Closing the issue cause it's alright just how it is
