### ISSUE TITLE
Another way to write anonymous comments

### ISSUE THREAD

**Issue by drendog** [UNICT-DMI/Telegram-SpottedDMI-Bot#132]
Just use a channel and start the message with a command

**Comment by alepiaz** [comment]
Solution: restrict channels from commenting in the group
Is this only a premium feature, though?

**Comment by drendog** [comment]
it's only premium feature, and you can't restrict channel from commenting by managing the group

**Comment by alepiaz** [comment]
I mean, force the bot to delete comments, or any message to be fair, coming from channels

**Comment by drendog** [comment]
actually the bot can remove any messages from channel, but it can't remove the commands sent by channel. Removing all commands from community can be a solution, but it will avoid to use commands ad hoc for community (not implemented yet) in the future
