### ISSUE TITLE
Commands not displayed on "Menu"

### ISSUE THREAD

**Issue by Picred** [UNICT-DMI/Telegram-SpottedDMI-Bot#144]
On the bot's "Menu" button, not all the commands that can be used are displayed.
![menu-bot-bug](https://github.com/UNICT-DMI/Telegram-SpottedDMI-Bot/assets/102211437/9577a4c8-8aef-4a92-8cb0-a9276288539e)

**Comment by Helias** [comment]
what are the missing commands?

**Comment by Picred** [comment]
My bad, this is due to the recent refactor. Before that there was more displayed commands.
