### ISSUE TITLE
Add more reactions

### ISSUE THREAD

**Issue by TendTo** [UNICT-DMI/Telegram-SpottedDMI-Bot#37]
There is no such thing as to many reactions (or maybe there is, I don't know). So why not add more?

Simply edit the _data/yaml/reactions.yaml.dist_ file to add any one you like and the arrange them to your liking in the rows section. 

Just be mindful to not change the keys for already excising reactions, since otherwise the already stored votes stop referring to the reaction that generated them.

Examples:
```yaml
reactions:
  "0": 👎
  "1": 👍
  "2": 🤣
  "3": 😡
  "4": 🥰
rows: [
  ["1", "0"], 
  ["2", "3", "4"]
  ]
```
```yaml
reactions:
  "3": 😡
rows: [
  ["3"], 
  ["3", "3"], 
  ["3", "3", "3"],
  ["3", "3"],
  ["3"]
  ]
```
```yaml
reactions:
  "0": 🥰
  "1": 👍
rows: [
  ["0", "1"], 
  ]
```

**Comment by Helias** [comment]
what about closing this issue?
