### ISSUE TITLE
Exclude the first comment from the comment counter

### ISSUE THREAD

**Issue by Alessandrus00** [UNICT-DMI/Telegram-SpottedDMI-Bot#41]
Is there a way to remove from the comment counter of a spot the random nick comment?
When I see 1 comment below a spot I think that someone commented the spot, but it's just the anonymous random picked name.

![counter](https://user-images.githubusercontent.com/77611890/113489406-68578880-94c4-11eb-8bef-e99323c060a3.png)
![anonymous](https://user-images.githubusercontent.com/77611890/113489418-77d6d180-94c4-11eb-9d30-ce9bbaabbb38.png)

**Comment by TendTo** [comment]
While this is a welcome suggestion, I fear it's not possible. 

The "comment system" is handled by telegram, and we have very limited control over it. 
That "anonymous random picked name" message is needed to append the voting keyboard, and making it not appear in the counter would mean it would not show up in the comments too.
Furthermore, if we were to move the "voting keyboard" on the main channel, it would remove the connection tooltip altogether.

If you have some ideas or suggestion on how to avoid the problem, feel free to try and propose them.
