### ISSUE TITLE
Notify user when there is a new message in a thread

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/Telegram-SpottedDMI-Bot#56]
issue: when an user add a comment in a thread he will not receive a telegram notification

how to solve: we could use SpottedDMIBot to notify the user (sending a private message) when he joins a thread and there is some update

thx Giorgio & Rosario

**Comment by Helias** [comment]
reminder

**Comment by drendog** [comment]
My solution: 
When the native reactions will be implemented and will remain under the report button, a button could be added to follow the spot. This button allows you to receive notifications for a specific spot you want to follow. If a user hasn't started a private chat with the bot, it will be impossible to receive the notification, so in this case the user should receive an alert that suggests to start the chat with the bot.
