### ISSUE TITLE
Follow Button

### ISSUE THREAD

**Issue by drendog** [UNICT-DMI/Telegram-SpottedDMI-Bot#72]
When the native reactions will be implemented and will remain under the report button, a button could be added to follow the spot. This button allows you to receive notifications for a specific spot you want to follow. If a user hasn't started a private chat with the bot, it will be impossible to receive the notification, so in this case the user should receive an alert that suggests to start the chat with the bot.

**Comment by Helias** [comment]
duplicate https://github.com/UNICT-DMI/Telegram-SpottedDMI-Bot/issues/56
